# [START swagger]
swagger: "2.0"
info:
  description: "Documentation for the Kademlia WoT RESTful API"
  title: "KademliaGolf"
  version: "1.0.0"
# [END swagger]
basePath: "/api/sensors"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "http"
paths:
  "/temperature/value":
    get:
      description: "Get the current temperature measured by the sensor"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/temperature"
  "/humidity/value":
    get:
      description: "Get the current humidity measured by the sensor"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/humidity"
  "/led/toogle":
    put:
      description: "Toggle the LED connected to the pi"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/led"
definitions:
  temperature:
    properties:
      currentTime:
        type: "string"
        description: "Date and time of the measurement"
      temperature:
        type: "number"
        description: "Value of the temperature, given in celsius"
  humidity:
    properties:
      currentTime:
        type: "string"
        description: "Date and time of the measurement"
      humidity:
        type: "number"
        description: "Value of the humidity, given in percentage"
  led:
    properties:
      currentState:
        type: "boolean"
        description: "The state the LED changed to. True is ON, and false is OFF"
      currentTime:
        type: "string"
        description: "Date and time of the request"
      message:
        type: "string"
        description: "Toggled!"